trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'artur123231/flask-app'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        command: buildAndPush
        containerRegistry: 'Docker connection'
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest
